services:
  app:
    build:
      context: ./app
    expose:
      - 7000
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
  platform:
    image: php:apache
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - app